# Generated by Django 5.2.7 on 2025-11-11 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='queue',
            name='name',
            field=models.CharField(default='Default Queue', max_length=200),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueentry',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.queue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('registration', 'Registration'), ('queue_joined', 'Queue Joined'), ('queue_position', 'Queue Position Update'), ('ready', 'Your Turn is Ready')], default='registration', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
